name: Deploy

on:
  push:
    branches:
      - main  # Branch yang akan memicu deploy otomatis

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: 139.180.145.92 
        username: root  # Username VPS kamu
        password: ${{ secrets.VPS_PASSWORD }}  # Password disimpan di Secrets GitHub
        port: 22
        script: |
          cd /var/www/tes-cicd
          git pull origin main
          composer install --no-dev --prefer-dist
          php artisan migrate --force
          php artisan cache:clear
          php artisan config:cache
          php artisan route:cache
          sudo systemctl restart nginx
